In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas_datareader as data_reader
import yfinance as yf
import plotly.graph_objects as go
from datetime import datetime

Initializing the date time and fetching the stock data

In [4]:
end = datetime.now().date()
start = datetime(end.year - 1, end.month, end.day).date()
stock = 'AAPL'

df = yf.download(stock, start, end)

print(f"Default time of data is 1 yr from {end} to {start}")
df.head()

[*********************100%***********************]  1 of 1 completed

Default time of data is 1 yr from 2026-06-25 to 2025-06-25

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2025-06-25  200.763535  202.865198  199.827247  200.653969  39525700
2025-06-26  200.205750  201.839268  198.671842  200.634043  50799100
2025-06-27  200.285431  202.416974  199.209697  201.092228  73188600
2025-06-30  204.359253  206.570482  198.472603  201.211736  91912800
2025-07-01  206.998795  209.359425  205.325425  205.853330  78788900

In [5]:
df = df.reset_index()
df.head()

Price        Date       Close        High         Low        Open    Volume
Ticker                   AAPL        AAPL        AAPL        AAPL      AAPL
0      2025-06-25  200.763535  202.865198  199.827247  200.653969  39525700
1      2025-06-26  200.205750  201.839268  198.671842  200.634043  50799100
2      2025-06-27  200.285431  202.416974  199.209697  201.092228  73188600
3      2025-06-30  204.359253  206.570482  198.472603  201.211736  91912800
4      2025-07-01  206.998795  209.359425  205.325425  205.853330  78788900

In [6]:
df = df.drop(['Date'], axis=1)
df.head()

/tmp/ipykernel_15444/2218488136.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  df = df.drop(['Date'], axis=1)

Price        Close        High         Low        Open    Volume
Ticker        AAPL        AAPL        AAPL        AAPL      AAPL
0       200.763535  202.865198  199.827247  200.653969  39525700
1       200.205750  201.839268  198.671842  200.634043  50799100
2       200.285431  202.416974  199.209697  201.092228  73188600
3       204.359253  206.570482  198.472603  201.211736  91912800
4       206.998795  209.359425  205.325425  205.853330  78788900

Making an interactive graph of the stock from real data

In [7]:
fig = go.Figure(
    data=[go.Candlestick(
        x=df.index,
        open=df['Open'],
        high=df['High'],
        low=df['Low'],
        close=df['Close']
    )]
)

fig.update_layout(title=f'{stock} Chart', yaxis_title='Price')
fig.show()